# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  unit-test:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "npm i"
      - run:
          name: "Run unit tests"
          command: "npm run test"
  coverage:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "npm i"
      - run:
          name: "Run unit tests with coverage"
          command: "npm run test:coverage"
      - store_artifacts:
          path: coverage

workflows:
  main-workflow:
    jobs:
      - unit-test
      - coverage
